### PR TITLE
SAML Group links

### PR DESCRIPTION
**Pull request by yantantether**
Adds new group config item `group_saml_links`
Similar functionality to group_ldap_links
Requires response mapping from `name` to `saml_group_name` Support enforce delete

#549

### CODE REVIEW

**Comment by yantantether** [comment]
Quick update. I've worked around using Gitlab.com by supplying a top level group parent group ID as an env-var.
I won't commit that for this PR but I'm unblocked

**Comment by yantantether** [comment]
Hi @gdubicki 

I've pushed a single acceptance test. I had to call Gitlab API to grab a hydrated group, as the `group_for_function` was just the stub after fixture creation. Not sure if you want that API call in the test itself or have a better place. Still getting my head around the structure.

I also couldn't see an example of using Gitlab API in the functional codebase. Can you point me to an example? Otherwise is this good enough?

Happy to make further changes with feedback of course.

**Comment by gdubicki** [comment]
Huh, any ideas why the acceptance tests fail with HTTP 401:
```
E               gitlabform.gitlab.core.UnexpectedResponseException: Request url='http://localhost/api/v4/groups/13/saml_group_links?per_page=100', method=GET, failed - expected code(s) [200, 404], got code 401 & body: '{"message":"401 Unauthorized"}'
```
@yantantether ? 🤔

**Comment by yantantether** [comment]
Hi @gdubicki,

Has the premium licence for automated tests expired? Line 66 in the log:

```
GitLab version:
{"version":"16.0.1-ee","revision":"29e1314f910","kas":{"enabled":true,"externalUrl":"ws://localhost/-/kubernetes-agent/","version":"v16.0.1"},"enterprise":true}
GitLab license (plan, is expired?):
"premium"
false
```

If that's a red herring, my immediate thought was that I had manually enabled SAML in the Gitlab.com UI, and disabled 'enforce SSO-only authentication'. I think it could be setup in the Gitlab Omnibus config. I guess something like this, but I can't see anything obvious on disabling SSO enforcement.

```
gitlab_rails['omniauth_enabled'] = true
gitlab_rails['omniauth_providers'] = [{ name: 'group_saml' }]
```

I can't test this without a premium licence though. Do you know of a way to get a premium licence for development?

**Comment by amimas** [comment]
> Huh, any ideas why the acceptance tests fail with HTTP 401:
> 
> ```
> E               gitlabform.gitlab.core.UnexpectedResponseException: Request url='http://localhost/api/v4/groups/13/saml_group_links?per_page=100', method=GET, failed - expected code(s) [200, 404], got code 401 & body: '{"message":"401 Unauthorized"}'
> ```
> 
> @yantantether ? 🤔

This was likely due to latest version of GitLab being used at the time, which introduced a change on access token requiring an expiry date. It was fixed in https://github.com/gitlabform/gitlabform/pull/557.

@yantantether - A bunch of other updates have been merged recently. Could you please try updating your PR branch?

> I can't test this without a premium licence though. Do you know of a way to get a premium licence for development?

I signed up for GitLab Trial. That only gives me a license for 30 days though. Will need to request for a renewal or extension later again.

**Comment by amimas** [comment]
@yantantether - Are you available to continue with this PR?

**Comment by amimas** [comment]
@yantantether - just checking if you're able to continue with this.

**Comment by yantantether** [comment]
Hi @amimas, sorry for not replying before. Yes I would like to continue with this PR.
I got stuck with the licence issue. I'll try and get a temp one.
Also struggling for time, but who isn't

**Comment by amimas** [comment]
Hi @yantantether - no worries at all. Great that you're willing to continue with it. Thanks so much.

A lot of updates took place lately. You'd want to update your branch. When you're able to pick this up again, could you please switch your implementation to year the`python-gitlab` library? The project recently stated using the library and couple of features have been migrated to use the library. See [this github project](https://github.com/orgs/gitlabform/projects/1) for progress and references to features that use the library now. I'm assuming this feature can be done using the library.

Thanks again.

**Comment by TimKnight-DWP** [comment]
Released in v3.12.0

**Comment by gdubicki** [comment]
Hey @yantantether! As this has been released in gitlabform, could you perhaps pull down [your fork](https://pypi.org/project/gitlabform-ytt/) from PyPI? It may confuse someone if they don't read your README and you know how good ~the users are~ everyone is with reading those... 😅

**Pull request closed without merging**
