### PR TITLE
test: refactor test_files, test_branches and conftest to support better test encapsulation

### PR DESCRIPTION
**Pull request by TimKnight-DWP**
- Should reduce chances of tests clashing with project/branch names etc

### CODE REVIEW

**Review by amimas — COMMENTED** [review]
Hi @TimKnight-DWP  - Thanks for the PR. I haven't come across or seen any issues with tests clashing. Could you share some details please?

I'm not yet familiar with the `test_file*.py` and where it's used. Probably need some time to take a closer look. But just not sure what is being solved.

If @gdubicki is available, it might be quick review for him.

**Comment by TimKnight-DWP** [comment]
It's one of those infrequent, but annoying to debug issues, as it's next to impossible to reproduce consistently, this change is applying some common strategies I've used to mitigate these sorts of issues

**Comment by amimas** [comment]
Thanks for explaining @TimKnight-DWP . I haven't experienced that, but maybe because I don't actually run the full test suite locally. Usually only run the test cases related to a specific processor. I know there is a known issue with tests randomly failing in GitHub Actions involving committing a readme file to project. See issue #596. Is this PR potentially going to resolve that or have you seen other kinds of test issues?

I briefly skimmed through the changes and I think it's good to merge. All the tests are still passing, which is good.

**Comment by amimas** [comment]
Hi @TimKnight-DWP - looks like the there's a test failure in latest pipeline at the moment.

https://github.com/gitlabform/gitlabform/actions/runs/8925985636/job/24515984764?pr=744

I feel this is a flaky test and probably will pass with a rerun. But I haven't seen this before. Since you're trying at stabilize the tests with this PR, do you want to take a look at the current failure?

**Comment by gdubicki** [comment]
Frankly I do not get why this change would help with test flakiness, but it does make the code less duplicated so I am for at least for that reason. Thank you, @TimKnight-DWP !

**Review by gdubicki — APPROVED** [review]

**Comment by TimKnight-DWP** [comment]
@gdubicki my gut feeling is there is some thread/handover going on somewhere, which can result in the yield from `project` fixture not being invoked before the next test class executes, meaning it ends up using the same project and has clashing file contents. Moving to by fixture, a) as you say reduces duplication and b) should hopefully result in a cleaner test execution, especially with projects getting slightly more unique names

**Comment by TimKnight-DWP** [comment]
@amimas if my gut feeling is right than inheritance_break.py will be the same issue, but additionally having now read the test it is not clear exactly what it does, so I will rename and then try fold into a more appropriate test file

**Comment by TimKnight-DWP** [comment]
This may relate to #596 (intermittent errors with README etc)

**Review by amimas — APPROVED** [review]
Thanks @TimKnight-DWP again for looking into this. I noticed on several occasions recently where tests are failing in github actions with following error:

```
FAILED tests/acceptance/standard/test_files_protected.py::TestFilesProtected::test__set_file_protected_branches - AssertionError: assert 'Content for all branches' == 'Default README content.'
```

https://github.com/gitlabform/gitlabform/actions/runs/8993858128/job/24706391920?pr=748

Is this what you have been running into? Not sure why this started happening recently. Wouldn't be surprised if this is somehow caused by latest version of GitLab, since that's what we use in our tests.

Anyways, I agree with @gdubicki . I think this PR is addressing some chores related to tests and if this does help with test flakiness, that's even better. Would love to see this being merged. I'll leave it to you to merge.

**Comment by TimKnight-DWP** [comment]
@amimas yes that was the test failure I spotted. I know in GL 16 a lot more actions (like delete) happen asynchronously from my testing re-work on python-gitlab, tldr Deletes get put onto a Queue. So it makes it even harder to tidy up effectively, ideally we'd want to be even more sure we got a new branch everytime, but we're using a random string generator so it's hard to do without making the test object names harder to read by say putting in a UUID

**Pull request merged**
