### PR TITLE
feat: add saml group links

### PR DESCRIPTION
**Pull request by oliverbaehler**
Implements the following issue #549
I am not really knowledgable when it comes to Python :D.

### CODE REVIEW

**Comment by gdubicki** [comment]
Hey, @oliverbaehler! Thank you for the contribution!

However, we don't want to add any more code using our built-in GitLab library as we are migration to use [python-gitlab](https://python-gitlab.readthedocs.io/en/stable/) everywhere. Could you try to rewrite your code to use it?

Also please check the failed unit tests and remember to reformat your code with black (or use `pre-commit` to make git run it for you - see https://gitlabform.github.io/gitlabform/contrib/coding_guidelines/).

**Review by gdubicki — CHANGES_REQUESTED** [review]
Hey, @oliverbaehler! Thank you for the contribution!

However, we don't want to add any more code using our built-in GitLab library as we are migration to use [python-gitlab](https://python-gitlab.readthedocs.io/en/stable/) everywhere. Could you try to rewrite your code to use it?

Also please check the failed unit tests and remember to reformat your code with black (or use pre-commit to make git run it for you - see https://gitlabform.github.io/gitlabform/contrib/coding_guidelines/).

**Comment by TimKnight-DWP** [comment]
Additionally we should be trying to add Tests both Unit and Integration to ensure/define the YAML schema working as expected

**Comment by oliverbaehler** [comment]
I solved this use-case for a customer with terraform. Sorry no time to implement further.

**Comment by gdubicki** [comment]
See https://github.com/gitlabform/gitlabform/pull/755 instead.

**Pull request closed without merging**
