### PR TITLE
fix: ignore keep_bots from users list for group membership

### LINKED ISSUE #553: Group membership fails to apply when using keep_bots attribute
## Description

Following fails to apply group membership - 

```yaml
config_version: 3
gitlab:
  ssl_verify: true
  timeout: 2
projects_and_groups:
  "GroupA/GroupB/*":
    group_members:
      keep_bots: true
      enforce: true
      groups:
        xx/users-reporter:
          group_access: reporter
        yy/users-guest:
          group_access: guest
```

Use following command to replicate this issue - 

```sh
gitlabform -c above-config.yaml GroupA/GroupB/GroupC -os group_settings,group_members
```

I'm getting below error message - 

```
🏗 GitLabForm version: 3.6.0 = the latest stable 😊
Warning: Connected as non-admin. You may encounter permission issues.
>>> Getting requested groups or projects...
:: # of groups to process: 1
:: # of projects to process: 0
@ (1/1) Processing group: GroupA/GroupB/GroupC 
Warning: Error occurred while processing group GroupA/GroupB/GroupC, exception:

'bool' object is not subscriptable
:: # of groups processed successfully: 0
:: # of projects processed successfully: 0
:: # of groups failed: 1 
:: Failed group 1: GroupA/GroupB/GroupC
```

On debugging it seems the user list for group membership had following item - 

```
keep_bots: true
```

### Gitlabform version 

```sh
% gitlabform --version                                                                                  
🏗 GitLabForm version: 3.6.0 = the latest stable 😊
```

### Gitlab version

GitLab Enterprise Edition 16.1.0-pre [c5ac07d12dc](https://gitlab.com/gitlab-org/gitlab/-/commits/c5ac07d12dc)

### PR DESCRIPTION
**Pull request by SachinKSingh28**
Fixes #553

### CODE REVIEW

**Comment by SachinKSingh28** [comment]
@gdubicki added some tests and reproduced the issue here - https://github.com/gitlabform/gitlabform/actions/runs/5321557164/jobs/9636799769?pr=554#step:5:951

**Comment by adam-moss** [comment]
@gdubicki is there anything more we need to do to get this merged?

**Comment by amimas** [comment]
The failures mentioned above is because the gitlab instance setup process involves creating an access token. This access token is used in the acceptance test api calls. The access token is currently being created without an expiry date.

In the CI where acceptance test is run, latest version of gitlab is being used. As of GitLab v16, access tokens cannot be created without an expiry date. That leads to access token not being setup. Hence the `401 Unauthorized` error.

https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html

> The ability to create personal access tokens without expiry was [deprecated](https://gitlab.com/gitlab-org/gitlab/-/issues/369122) in GitLab 15.4 and [removed](https://gitlab.com/gitlab-org/gitlab/-/issues/392855) in GitLab 16.0. In GitLab 16.0 and later, existing personal access tokens without an expiry date are automatically given an expiry date of 365 days later than the current date. The automatic adding of an expiry date occurs on GitLab.com during the 16.0 milestone. The automatic adding of an expiry date occurs on self-managed instances when they are upgraded to GitLab 16.0. This change is a breaking change.

I'll try open a PR to fix when I can get to it.

**Comment by gdubicki** [comment]
Thanks a lot, @amimas! I wasn’t able to find the time to troubleshoot it successfully..

**Comment by amimas** [comment]
@SachinKSingh28 - The CI issue should be resolved now. Could you please update your branch? Also, found couple of failures related to "keep bots" feature while the CI issue was being fixed. See here for details: https://github.com/gitlabform/gitlabform/pull/557#issuecomment-1631165349

Please update the test cases accordingly to resolve those failures. Thanks so much for your help and contribution.

**Comment by gdubicki** [comment]
> Also, found couple of failures related to "keep bots" feature while the CI issue was being fixed. See here for details: [#557 (comment)](https://github.com/gitlabform/gitlabform/pull/557#issuecomment-1631165349)

I fixed those in https://github.com/gitlabform/gitlabform/commit/d2b0c8182b4e12c9aec1e0dc3b83e1c06c2fe3d8 and I updated this branch with it.

**Review by gdubicki — APPROVED** [review]

**Comment by amimas** [comment]
Anything else outstanding for this or is this ready to merge? The PR is still in draft state.

cc: @SachinKSingh28

**Comment by SachinKSingh28** [comment]
Nope! All good. I'll remove the draft state. Thanks for fixing the issues with tests.

**Comment by SachinKSingh28** [comment]
Some checks are failing I'll take a look soon.

**Comment by gdubicki** [comment]
> Don't know what this one is about -
> 
> > Waiting for review: Integrate Pull Request needs approval to start deploying changes.

This is the way we run acceptance tests that require the premium license. But I approved it already and it has passed: https://github.com/gitlabform/gitlabform/actions/runs/5546123039/jobs/10125973077?pr=554

😊

**Pull request merged**
