### PR TITLE
Support multiple approval rules

### PR DESCRIPTION
**Pull request by poffey21**
With GitLab Premium and above, multiple approval rules are supported. Moreover, [name-specific](https://docs.gitlab.com/ee/user/application_security/#security-approvals-in-merge-requests) rules can be leveraged to create dynamic rules.  This rule allows multiple rules to be created:

```yaml
group_settings:
  'test-group':
    merge_requests:
      approvals:
        approvals_before_merge: 1
        reset_approvals_on_push: true
        disable_overriding_approvers_per_merge_request: true
      approvers:
        - poffey21
      approval_rules:
        Vulnerability-Check:
          approvers:
          - poffey21
```

or 

```yaml
group_settings:
  'test-group':
    merge_requests:
      approvals:
        approvals_before_merge: 1
        reset_approvals_on_push: true
        disable_overriding_approvers_per_merge_request: true
      approvers:
        - poffey21
      approval_rules:
        Vulnerability-Check:
          approvers:
          - poffey21
```

or 

```yaml
group_settings:
  'test-group':
    merge_requests:
      approvals:
        approvals_before_merge: 1
        reset_approvals_on_push: true
        disable_overriding_approvers_per_merge_request: true
      approval_rules:
        Vulnerability-Check:
          approvers:
          - poffey21
```

### CODE REVIEW

**Comment by gdubicki** [comment]
(This would implement #95.)

**Comment by gdubicki** [comment]
Hey @poffey21 , thanks a lot for the contribution! 😊🙏

However I would like to ask you for a few things before we can merge it:
* please provide examples of how to use this feature as changes to `config.yml`, as it is the de facto user manual, plus add the feature to the list of features in `README.md`,
* please add the integration tests,
* please format the code with Black - see the failed check above,

**Review by gdubicki — CHANGES_REQUESTED** [review]
I would like to ask you for a few things before we can merge it:

* please provide examples of how to use this feature as changes to config.yml, as it is the de facto user manual, plus add the feature to the list of features in README.md,
* please add the integration tests,
* please format the code with Black - see the failed check above,

**Comment by gdubicki** [comment]
Hey @poffey21 ! Is there a chance you will get back to this PR and continue working on it? Please answer honestly as maybe we can open this for other people to continue.

**Comment by poffey21** [comment]
@gdubicki I will pick this back up this upcoming week. Thanks for the ping!

**Comment by Mahpara93** [comment]
@gdubicki  @poffey21  when would this feature be available for use? We planning to use multi-approval rules for few of our repos. Thank you for your contribution :).

**Comment by Siythrun** [comment]
Is there any more traction on this change? Would be good to see approvals_required and approver_groups added to this as well.

**Comment by gdubicki** [comment]
Frankly we don't have a Premium GitLab license so we are not highly motivated to implement it ourselves, @Siythrun . We are open to PRs though!

**Comment by vchepkov** [comment]
This was open for more than a year, I would be happy to test, since we use EE edition.
Github shows me no changes though

**Comment by gdubicki** [comment]
> This was open for more than a year, I would be happy to test, since we use EE edition. Github shows me no changes though

I think you would have to go through each commit here, check its diff and possibly cherry-pick what is good to another branch.

**Comment by yashwanth-l** [comment]
any timeline on when this feature would be available with gitlabform?

**Comment by gdubicki** [comment]
@yashwanth-l: as mentioned in https://github.com/gitlabform/gitlabform/issues/388, in September I will have access to license that supports multiple approval rules. Then I can and most probably will implement this feature on my own as this is something that we would need ourselves at Egnyte. So it should be released in September/October.

**Comment by gdubicki** [comment]
Closing as outdated, but thanks for your work on this anyway, @poffey21! I will create a new PR in its place.

**Pull request closed without merging**
